apiVersion: v1
kind: Service
metadata:
  labels:
    app: alfresco-test
  name: alfresco-test
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: alfresco-test
